#!/bin/bash -ex
#./configure_hosts.py
#./expect.py host_script.yml host1 host2
ansible-playbook test_collection.yml -K
#./configure_routers.py
#./expect.py router_script.yml vyos_r1 vyos_r2
ansible-playbook test_collection2.yml -K
./ping_all
