---
- benthomasson.expect.expect:
    command: "sudo virsh console {{node.name}}"
    script:
        - expect: "password for.*:"
        - send: "{{state.passwd}}"
        - send: "\n"
        - send: "\n"
        - expect: "Connected to domain"
        - send: "\n"
        - expect: "login:"
        - send: "root\n"
        - logfile: "{{node.name}}.log"
        - expect: "#"
        - send: "echo 'auto lo\niface lo inet loopback\nauto eth0\niface eth0 inet dhcp\n' > /etc/network/interfaces\n"
        - expect: "#"
        - send: "apk add openssh\n"
        - expect: "#"
        - send: "echo 'PermitRootLogin yes' >>  /etc/ssh/sshd_config\n"
        - expect: "#"
        - send: "/etc/init.d/sshd start\n"
        - expect: "#"
        - send: "/etc/init.d/networking restart\n"
        - expect: "#"
        - send: "mkdir -p ~/.ssh\n"
        - expect: "#"
        - send: "chmod 700 .ssh\n"
        - expect: "#"
        - send: "echo '{{state.key}}' >> .ssh/authorized_keys\n"
        - expect: "#"
        - send: "echo 'http://nl.alpinelinux.org/alpine/v3.12/main/' >> /etc/apk/repositories\n"
        - expect: "#"
        - send: "apk update\n"
        - expect: "#"
        - send: "apk add python3\n"
        - expect: "#"
        - send: "exit\n"
...
