---
- benthomasson.expect.expect:
    command: "sudo virsh console {{node.name}}"
    script:
        - expect: "password for.*:"
        - send: "{{state.passwd}}"
        - send: "\n"
        - send: "\n"
        - expect: "Connected to domain"
        - send: "\n"
        - expect: "login:"
        - send: "vyos\n"
        - expect: "Password:"
        - send: "vyos\n"
        - logfile: "{{node.name}}.log"
        - expect: "$"
        - send: "\n"
        - expect: "$"
        - send: "configure\n"
        - expect: "#"
        - send: "set interfaces ethernet eth0 address dhcp\n"
        - expect: "#"
        - send: "set service ssh port 22\n"
        - expect: "#"
        - send: "commit\n"
        - expect: "#"
        - send: "save\n"
        - expect: "#"
        - send: "exit\n"
        - expect: "$"
        - send: "mkdir -p ~/.ssh\n"
        - expect: "$"
        - send: "chmod 700 .ssh\n"
        - expect: "$"
        - send: "echo '{{state.key}}' >> .ssh/authorized_keys\n"
        - expect: "$"
        - send: "chmod 600 .ssh/authorized_keys\n"
        - expect: "$"
        - send: "exit\n"
        - expect: "logout"
...
